CREATE TABLE Enum_Role (id INT AUTO_INCREMENT NOT NULL, role VARCHAR(40) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE Guild (id INT AUTO_INCREMENT NOT NULL, realm_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, guild_key VARCHAR(10) NOT NULL, INDEX IDX_B48152AF9DFF5F89 (realm_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE Member (id INT AUTO_INCREMENT NOT NULL, guild_id INT DEFAULT NULL, role_id INT DEFAULT NULL, realm_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, INDEX IDX_7748FF4E5F2131EF (guild_id), INDEX IDX_7748FF4ED60322AC (role_id), INDEX IDX_7748FF4E9DFF5F89 (realm_id), UNIQUE INDEX unique_member (guild_id, name, realm_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE Realm (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(40) NOT NULL, region VARCHAR(2) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
ALTER TABLE Guild ADD CONSTRAINT FK_B48152AF9DFF5F89 FOREIGN KEY (realm_id) REFERENCES Realm (id);
ALTER TABLE Member ADD CONSTRAINT FK_7748FF4E5F2131EF FOREIGN KEY (guild_id) REFERENCES Guild (id);
ALTER TABLE Member ADD CONSTRAINT FK_7748FF4ED60322AC FOREIGN KEY (role_id) REFERENCES Enum_Role (id);
ALTER TABLE Member ADD CONSTRAINT FK_7748FF4E9DFF5F89 FOREIGN KEY (realm_id) REFERENCES Realm (id);
