app:
    resource: "@WowGuildAudit/Controller/"
    type:     annotation

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

google_login:
    path: /login/check-google

logout:
    path: /logout

WowGuildAudit_ajax_add_team:
    path:  /guild/addTeam
    defaults: { _controller: WowGuildAudit:Guild:addTeam }

WowGuildAudit_ajax_remove_team:
    path:  /guild/removeTeam
    defaults: { _controller: WowGuildAudit:Guild:removeTeam }