# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        my_custom_hwi_provider:
            id: ib_user.oauth_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: true
            logout:
                path: /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
            oauth:
                resource_owners:
                    google:         "/login/check-google"
                login_path:       /login
                failure_path:       /login
                oauth_user_provider:
                    service: ib_user.oauth_user_provider

    access_control:
        - { path: ^/guild, roles: IS_AUTHENTICATED_ANONYMOUSLY }