# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
        secured_area:
            pattern: ^/google/
            anonymous: true
            logout: true
            oauth:
                resource_owners:
                    google:         "/google/login/check"
                login_path:       /google/login
                failure_path:     /google/login
                check_path:       /google/login/check

                oauth_user_provider:
                    service: app.provider.oauth

    access_control:
        - { path: ^/google, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/guild, roles: IS_AUTHENTICATED_FULLY }