# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
            anonymous: true
            logout:
                path: /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
            oauth:
                resource_owners:
                    google:         "/login/check-google"
                login_path:       /login
                failure_path:     /login
                check_path:       /connect_check
                provider: fos_userbundle

                oauth_user_provider:
                    service: app.provider.oauth

    access_control:
        - { path: ^/guild, roles: IS_AUTHENTICATED_FULLY }