# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.provider.oauth:
        class: WowGuildAudit\Provider\OAuthUserProvider
        arguments: ["@fos_user.user_manager",{facebook: facebookID, google: googleID}]