INSERT INTO realm (name, region) VALUES ("Aegwynn", "EU");
INSERT INTO realm (name, region) VALUES ("Aerie Peak", "EU");
INSERT INTO realm (name, region) VALUES ("Agamaggan", "EU");
INSERT INTO realm (name, region) VALUES ("Aggra (Português)", "EU");
INSERT INTO realm (name, region) VALUES ("Aggramar", "EU");
INSERT INTO realm (name, region) VALUES ("Ahn'Qiraj", "EU");
INSERT INTO realm (name, region) VALUES ("Al'Akir", "EU");
INSERT INTO realm (name, region) VALUES ("Alexstrasza", "EU");
INSERT INTO realm (name, region) VALUES ("Alleria", "EU");
INSERT INTO realm (name, region) VALUES ("Alonsus", "EU");
INSERT INTO realm (name, region) VALUES ("Aman'Thul", "EU");
INSERT INTO realm (name, region) VALUES ("Ambossar", "EU");
INSERT INTO realm (name, region) VALUES ("Anachronos", "EU");
INSERT INTO realm (name, region) VALUES ("Anetheron", "EU");
INSERT INTO realm (name, region) VALUES ("Antonidas", "EU");
INSERT INTO realm (name, region) VALUES ("Anub'arak", "EU");
INSERT INTO realm (name, region) VALUES ("Arak-arahm", "EU");
INSERT INTO realm (name, region) VALUES ("Arathi", "EU");
INSERT INTO realm (name, region) VALUES ("Arathor", "EU");
INSERT INTO realm (name, region) VALUES ("Archimonde", "EU");
INSERT INTO realm (name, region) VALUES ("Area 52", "EU");
INSERT INTO realm (name, region) VALUES ("Argent Dawn", "EU");
INSERT INTO realm (name, region) VALUES ("Arthas", "EU");
INSERT INTO realm (name, region) VALUES ("Arygos", "EU");
INSERT INTO realm (name, region) VALUES ("Ashenvale", "EU");
INSERT INTO realm (name, region) VALUES ("Aszune", "EU");
INSERT INTO realm (name, region) VALUES ("Auchindoun", "EU");
INSERT INTO realm (name, region) VALUES ("Azjol-Nerub", "EU");
INSERT INTO realm (name, region) VALUES ("Azshara", "EU");
INSERT INTO realm (name, region) VALUES ("Azuregos", "EU");
INSERT INTO realm (name, region) VALUES ("Azuremyst", "EU");
INSERT INTO realm (name, region) VALUES ("Baelgun", "EU");
INSERT INTO realm (name, region) VALUES ("Balnazzar", "EU");
INSERT INTO realm (name, region) VALUES ("Benedictus", "EU");
INSERT INTO realm (name, region) VALUES ("Beta Leveling Realm 01", "EU");
INSERT INTO realm (name, region) VALUES ("Beta Leveling Realm 03", "EU");
INSERT INTO realm (name, region) VALUES ("Beta Max Level PvP", "EU");
INSERT INTO realm (name, region) VALUES ("Blackhand", "EU");
INSERT INTO realm (name, region) VALUES ("Blackmoore", "EU");
INSERT INTO realm (name, region) VALUES ("Blackrock", "EU");
INSERT INTO realm (name, region) VALUES ("Blackscar", "EU");
INSERT INTO realm (name, region) VALUES ("Bladefist", "EU");
INSERT INTO realm (name, region) VALUES ("Blade's Edge", "EU");
INSERT INTO realm (name, region) VALUES ("Bloodfeather", "EU");
INSERT INTO realm (name, region) VALUES ("Bloodhoof", "EU");
INSERT INTO realm (name, region) VALUES ("Bloodscalp", "EU");
INSERT INTO realm (name, region) VALUES ("Blutkessel", "EU");
INSERT INTO realm (name, region) VALUES ("Booty Bay", "EU");
INSERT INTO realm (name, region) VALUES ("Borean Tundra", "EU");
INSERT INTO realm (name, region) VALUES ("Boulderfist", "EU");
INSERT INTO realm (name, region) VALUES ("Brill", "EU");
INSERT INTO realm (name, region) VALUES ("Bronze Dragonflight", "EU");
INSERT INTO realm (name, region) VALUES ("Bronzebeard", "EU");
INSERT INTO realm (name, region) VALUES ("Burning Blade", "EU");
INSERT INTO realm (name, region) VALUES ("Burning Legion", "EU");
INSERT INTO realm (name, region) VALUES ("Burning Steppes", "EU");
INSERT INTO realm (name, region) VALUES ("Chamber Of Aspects", "EU");
INSERT INTO realm (name, region) VALUES ("Chants éternels", "EU");
INSERT INTO realm (name, region) VALUES ("Cho'gall", "EU");
INSERT INTO realm (name, region) VALUES ("Chromaggus", "EU");
INSERT INTO realm (name, region) VALUES ("Colinas Pardas", "EU");
INSERT INTO realm (name, region) VALUES ("Confréri Du Thorium", "EU");
INSERT INTO realm (name, region) VALUES ("Conseil des Ombres", "EU");
INSERT INTO realm (name, region) VALUES ("Crushridge", "EU");
INSERT INTO realm (name, region) VALUES ("C'Thun", "EU");
INSERT INTO realm (name, region) VALUES ("Culte de la Rive noire", "EU");
INSERT INTO realm (name, region) VALUES ("Daggerspine", "EU");
INSERT INTO realm (name, region) VALUES ("Dalaran", "EU");
INSERT INTO realm (name, region) VALUES ("Dalvengyr", "EU");
INSERT INTO realm (name, region) VALUES ("Darkmoon Faire", "EU");
INSERT INTO realm (name, region) VALUES ("Darksorrow", "EU");
INSERT INTO realm (name, region) VALUES ("Darkspear", "EU");
INSERT INTO realm (name, region) VALUES ("Das Konsortium", "EU");
INSERT INTO realm (name, region) VALUES ("Das Syndikat", "EU");
INSERT INTO realm (name, region) VALUES ("Deathguard", "EU");
INSERT INTO realm (name, region) VALUES ("Deathweaver", "EU");
INSERT INTO realm (name, region) VALUES ("Deathwing", "EU");
INSERT INTO realm (name, region) VALUES ("Deepholm", "EU");
INSERT INTO realm (name, region) VALUES ("Defias Brotherhood", "EU");
INSERT INTO realm (name, region) VALUES ("Dentarg", "EU");
INSERT INTO realm (name, region) VALUES ("Der Abyssische Rat", "EU");
INSERT INTO realm (name, region) VALUES ("Der Mithrilorden", "EU");
INSERT INTO realm (name, region) VALUES ("Der Rat Von Dalaran", "EU");
INSERT INTO realm (name, region) VALUES ("Destromath", "EU");
INSERT INTO realm (name, region) VALUES ("Dethecus", "EU");
INSERT INTO realm (name, region) VALUES ("Die Aldor", "EU");
INSERT INTO realm (name, region) VALUES ("Die Arguswacht", "EU");
INSERT INTO realm (name, region) VALUES ("Die Ewige Wacht", "EU");
INSERT INTO realm (name, region) VALUES ("Die Nachtwache", "EU");
INSERT INTO realm (name, region) VALUES ("Die Silberne Hand", "EU");
INSERT INTO realm (name, region) VALUES ("Die Todeskrallen", "EU");
INSERT INTO realm (name, region) VALUES ("Doomhammer", "EU");
INSERT INTO realm (name, region) VALUES ("Draenor", "EU");
INSERT INTO realm (name, region) VALUES ("Dragonblight", "EU");
INSERT INTO realm (name, region) VALUES ("Dragonmaw", "EU");
INSERT INTO realm (name, region) VALUES ("Drak'thul", "EU");
INSERT INTO realm (name, region) VALUES ("Drek'Thar", "EU");
INSERT INTO realm (name, region) VALUES ("Dun Modr", "EU");
INSERT INTO realm (name, region) VALUES ("Dun Morogh", "EU");
INSERT INTO realm (name, region) VALUES ("Dunemaul", "EU");
INSERT INTO realm (name, region) VALUES ("Durotan", "EU");
INSERT INTO realm (name, region) VALUES ("Earthen Ring", "EU");
INSERT INTO realm (name, region) VALUES ("Echsenkessel", "EU");
INSERT INTO realm (name, region) VALUES ("Eitrigg", "EU");
INSERT INTO realm (name, region) VALUES ("Eldre'Thalas", "EU");
INSERT INTO realm (name, region) VALUES ("Elune", "EU");
INSERT INTO realm (name, region) VALUES ("Emerald Dream", "EU");
INSERT INTO realm (name, region) VALUES ("Emeriss", "EU");
INSERT INTO realm (name, region) VALUES ("Eonar", "EU");
INSERT INTO realm (name, region) VALUES ("Eredar", "EU");
INSERT INTO realm (name, region) VALUES ("Eversong", "EU");
INSERT INTO realm (name, region) VALUES ("Executus", "EU");
INSERT INTO realm (name, region) VALUES ("Exodar", "EU");
INSERT INTO realm (name, region) VALUES ("Festung der Stürme", "EU");
INSERT INTO realm (name, region) VALUES ("Fordragon", "EU");
INSERT INTO realm (name, region) VALUES ("Forscherliga", "EU");
INSERT INTO realm (name, region) VALUES ("Frostmane", "EU");
INSERT INTO realm (name, region) VALUES ("Frostmourne", "EU");
INSERT INTO realm (name, region) VALUES ("Frostwhisper", "EU");
INSERT INTO realm (name, region) VALUES ("Frostwolf", "EU");
INSERT INTO realm (name, region) VALUES ("Galakrond", "EU");
INSERT INTO realm (name, region) VALUES ("Garona", "EU");
INSERT INTO realm (name, region) VALUES ("Garrosh", "EU");
INSERT INTO realm (name, region) VALUES ("Genjuros", "EU");
INSERT INTO realm (name, region) VALUES ("Ghostlands", "EU");
INSERT INTO realm (name, region) VALUES ("Gilneas", "EU");
INSERT INTO realm (name, region) VALUES ("Goldrinn", "EU");
INSERT INTO realm (name, region) VALUES ("Gordunni", "EU");
INSERT INTO realm (name, region) VALUES ("Gorgonnash", "EU");
INSERT INTO realm (name, region) VALUES ("Greymane", "EU");
INSERT INTO realm (name, region) VALUES ("Grim Batol", "EU");
INSERT INTO realm (name, region) VALUES ("Grom", "EU");
INSERT INTO realm (name, region) VALUES ("Gul'dan", "EU");
INSERT INTO realm (name, region) VALUES ("Hakkar", "EU");
INSERT INTO realm (name, region) VALUES ("Haomarush", "EU");
INSERT INTO realm (name, region) VALUES ("Hellfire", "EU");
INSERT INTO realm (name, region) VALUES ("Hellscream", "EU");
INSERT INTO realm (name, region) VALUES ("Howling Fjord", "EU");
INSERT INTO realm (name, region) VALUES ("Hyjal", "EU");
INSERT INTO realm (name, region) VALUES ("Illidan", "EU");
INSERT INTO realm (name, region) VALUES ("Jaedenar", "EU");
INSERT INTO realm (name, region) VALUES ("Kael'thas", "EU");
INSERT INTO realm (name, region) VALUES ("Kalaran", "EU");
INSERT INTO realm (name, region) VALUES ("Karazhan", "EU");
INSERT INTO realm (name, region) VALUES ("Kargath", "EU");
INSERT INTO realm (name, region) VALUES ("Kazzak", "EU");
INSERT INTO realm (name, region) VALUES ("Kel'Thuzad", "EU");
INSERT INTO realm (name, region) VALUES ("Khadgar", "EU");
INSERT INTO realm (name, region) VALUES ("Khaz Modan", "EU");
INSERT INTO realm (name, region) VALUES ("Khaz'goroth", "EU");
INSERT INTO realm (name, region) VALUES ("Kil'jaeden", "EU");
INSERT INTO realm (name, region) VALUES ("Kilrogg", "EU");
INSERT INTO realm (name, region) VALUES ("Kirin Tor", "EU");
INSERT INTO realm (name, region) VALUES ("Kor'gall", "EU");
INSERT INTO realm (name, region) VALUES ("Krag'jin", "EU");
INSERT INTO realm (name, region) VALUES ("Krasus", "EU");
INSERT INTO realm (name, region) VALUES ("Kul Tiras", "EU");
INSERT INTO realm (name, region) VALUES ("Kult der Verdammten", "EU");
INSERT INTO realm (name, region) VALUES ("La Croisade ecarlate", "EU");
INSERT INTO realm (name, region) VALUES ("Laughing Skull", "EU");
INSERT INTO realm (name, region) VALUES ("Les Clairvoyants", "EU");
INSERT INTO realm (name, region) VALUES ("Les Sentinelles", "EU");
INSERT INTO realm (name, region) VALUES ("Lich King", "EU");
INSERT INTO realm (name, region) VALUES ("Lightbringer", "EU");
INSERT INTO realm (name, region) VALUES ("Lightning's Blade", "EU");
INSERT INTO realm (name, region) VALUES ("Lordaeron", "EU");
INSERT INTO realm (name, region) VALUES ("Los Errantes", "EU");
INSERT INTO realm (name, region) VALUES ("Lothar", "EU");
INSERT INTO realm (name, region) VALUES ("Lycanthoth", "EU");
INSERT INTO realm (name, region) VALUES ("Madmortem", "EU");
INSERT INTO realm (name, region) VALUES ("Magtheridon", "EU");
INSERT INTO realm (name, region) VALUES ("Malfurion", "EU");
INSERT INTO realm (name, region) VALUES ("Mal'Ganis", "EU");
INSERT INTO realm (name, region) VALUES ("Malorne", "EU");
INSERT INTO realm (name, region) VALUES ("Malygos", "EU");
INSERT INTO realm (name, region) VALUES ("Mannoroth", "EU");
INSERT INTO realm (name, region) VALUES ("Marecage de Zangar", "EU");
INSERT INTO realm (name, region) VALUES ("Mazrigos", "EU");
INSERT INTO realm (name, region) VALUES ("Medivh", "EU");
INSERT INTO realm (name, region) VALUES ("Minahonda", "EU");
INSERT INTO realm (name, region) VALUES ("Moonglade", "EU");
INSERT INTO realm (name, region) VALUES ("Mug'thol", "EU");
INSERT INTO realm (name, region) VALUES ("Nagrand", "EU");
INSERT INTO realm (name, region) VALUES ("Naralex", "EU");
INSERT INTO realm (name, region) VALUES ("Nathrezim", "EU");
INSERT INTO realm (name, region) VALUES ("Naxxramas", "EU");
INSERT INTO realm (name, region) VALUES ("Nazjatar", "EU");
INSERT INTO realm (name, region) VALUES ("Nefarian", "EU");
INSERT INTO realm (name, region) VALUES ("Nemesis", "EU");
INSERT INTO realm (name, region) VALUES ("Neptulon", "EU");
INSERT INTO realm (name, region) VALUES ("Nera'thor", "EU");
INSERT INTO realm (name, region) VALUES ("Ner'zhul", "EU");
INSERT INTO realm (name, region) VALUES ("Nethersturm", "EU");
INSERT INTO realm (name, region) VALUES ("Nordrassil", "EU");
INSERT INTO realm (name, region) VALUES ("Norgannon", "EU");
INSERT INTO realm (name, region) VALUES ("Nozdormu", "EU");
INSERT INTO realm (name, region) VALUES ("Onyxia", "EU");
INSERT INTO realm (name, region) VALUES ("Outland", "EU");
INSERT INTO realm (name, region) VALUES ("Perenolde", "EU");
INSERT INTO realm (name, region) VALUES ("Pozzo dell'Eternità", "EU");
INSERT INTO realm (name, region) VALUES ("Proudmoore", "EU");
INSERT INTO realm (name, region) VALUES ("Quel'Thalas", "EU");
INSERT INTO realm (name, region) VALUES ("Ragnaros", "EU");
INSERT INTO realm (name, region) VALUES ("Rajaxx", "EU");
INSERT INTO realm (name, region) VALUES ("Rashgarroth", "EU");
INSERT INTO realm (name, region) VALUES ("Ravencrest", "EU");
INSERT INTO realm (name, region) VALUES ("Ravenholdt", "EU");
INSERT INTO realm (name, region) VALUES ("Razuvious", "EU");
INSERT INTO realm (name, region) VALUES ("Rexxar", "EU");
INSERT INTO realm (name, region) VALUES ("Runetotem", "EU");
INSERT INTO realm (name, region) VALUES ("Sanguino", "EU");
INSERT INTO realm (name, region) VALUES ("Sargeras", "EU");
INSERT INTO realm (name, region) VALUES ("Saurfang", "EU");
INSERT INTO realm (name, region) VALUES ("Scarshield Legion", "EU");
INSERT INTO realm (name, region) VALUES ("Sen'jin", "EU");
INSERT INTO realm (name, region) VALUES ("Shadowsong", "EU");
INSERT INTO realm (name, region) VALUES ("Shattered Halls", "EU");
INSERT INTO realm (name, region) VALUES ("Shattered Hand", "EU");
INSERT INTO realm (name, region) VALUES ("Shattrath", "EU");
INSERT INTO realm (name, region) VALUES ("Shen'dralar", "EU");
INSERT INTO realm (name, region) VALUES ("Silvermoon", "EU");
INSERT INTO realm (name, region) VALUES ("Sinstralis", "EU");
INSERT INTO realm (name, region) VALUES ("Skullcrusher", "EU");
INSERT INTO realm (name, region) VALUES ("Soulflayer", "EU");
INSERT INTO realm (name, region) VALUES ("Spinebreaker", "EU");
INSERT INTO realm (name, region) VALUES ("Sporeggar", "EU");
INSERT INTO realm (name, region) VALUES ("Steamwheedle Cartel", "EU");
INSERT INTO realm (name, region) VALUES ("Stormrage", "EU");
INSERT INTO realm (name, region) VALUES ("Stormreaver", "EU");
INSERT INTO realm (name, region) VALUES ("Stormscale", "EU");
INSERT INTO realm (name, region) VALUES ("Sunstrider", "EU");
INSERT INTO realm (name, region) VALUES ("Suramar", "EU");
INSERT INTO realm (name, region) VALUES ("Sylvanas", "EU");
INSERT INTO realm (name, region) VALUES ("Taerar", "EU");
INSERT INTO realm (name, region) VALUES ("Talnivarr", "EU");
INSERT INTO realm (name, region) VALUES ("Tarren Mill", "EU");
INSERT INTO realm (name, region) VALUES ("Teldrassil", "EU");
INSERT INTO realm (name, region) VALUES ("Temple noir", "EU");
INSERT INTO realm (name, region) VALUES ("Terenas", "EU");
INSERT INTO realm (name, region) VALUES ("Terokkar", "EU");
INSERT INTO realm (name, region) VALUES ("Terrordar", "EU");
INSERT INTO realm (name, region) VALUES ("The Maelstrom", "EU");
INSERT INTO realm (name, region) VALUES ("The Sha'tar", "EU");
INSERT INTO realm (name, region) VALUES ("The Venture Co", "EU");
INSERT INTO realm (name, region) VALUES ("Theradras", "EU");
INSERT INTO realm (name, region) VALUES ("Thermaplugg", "EU");
INSERT INTO realm (name, region) VALUES ("Thrall", "EU");
INSERT INTO realm (name, region) VALUES ("Throk'Feroth", "EU");
INSERT INTO realm (name, region) VALUES ("Thunderhorn", "EU");
INSERT INTO realm (name, region) VALUES ("Tichondrius", "EU");
INSERT INTO realm (name, region) VALUES ("Tirion", "EU");
INSERT INTO realm (name, region) VALUES ("Todeswache", "EU");
INSERT INTO realm (name, region) VALUES ("Trollbane", "EU");
INSERT INTO realm (name, region) VALUES ("Turalyon", "EU");
INSERT INTO realm (name, region) VALUES ("Twilight's Hammer", "EU");
INSERT INTO realm (name, region) VALUES ("Twisting Nether", "EU");
INSERT INTO realm (name, region) VALUES ("Tyrande", "EU");
INSERT INTO realm (name, region) VALUES ("Uldaman", "EU");
INSERT INTO realm (name, region) VALUES ("Ulduar", "EU");
INSERT INTO realm (name, region) VALUES ("Uldum", "EU");
INSERT INTO realm (name, region) VALUES ("Un'Goro", "EU");
INSERT INTO realm (name, region) VALUES ("Varimathras", "EU");
INSERT INTO realm (name, region) VALUES ("Vashj", "EU");
INSERT INTO realm (name, region) VALUES ("Vek'lor", "EU");
INSERT INTO realm (name, region) VALUES ("Vek'nilash", "EU");
INSERT INTO realm (name, region) VALUES ("Vol'jin", "EU");
INSERT INTO realm (name, region) VALUES ("Wildhammer", "EU");
INSERT INTO realm (name, region) VALUES ("Wrathbringer", "EU");
INSERT INTO realm (name, region) VALUES ("Xavius", "EU");
INSERT INTO realm (name, region) VALUES ("Ysera", "EU");
INSERT INTO realm (name, region) VALUES ("Ysondre", "EU");
INSERT INTO realm (name, region) VALUES ("Zenedar", "EU");
INSERT INTO realm (name, region) VALUES ("Ревущий фьорд", "EU");
INSERT INTO realm (name, region) VALUES ("Гордунни", "EU");
INSERT INTO realm (name, region) VALUES ("Свежеватель Душ", "EU");
INSERT INTO realm (name, region) VALUES ("Ясеневый лес", "EU");
INSERT INTO realm (name, region) VALUES ("Черный Шрам", "EU");
INSERT INTO realm (name, region) VALUES ("Разувий", "EU");
INSERT INTO realm (name, region) VALUES ("Страж смерти", "EU");
INSERT INTO realm (name, region) VALUES ("Дракономор", "EU");
INSERT INTO realm (name, region) VALUES ("Азурегос", "EU");
INSERT INTO realm (name, region) VALUES ("Борейская тундра", "EU");
INSERT INTO realm (name, region) VALUES ("Вечная Песня", "EU");
INSERT INTO realm (name, region) VALUES ("Пиратская Бухта", "EU");
INSERT INTO realm (name, region) VALUES ("Голдринн", "EU");
INSERT INTO realm (name, region) VALUES ("Король-лич", "EU");
INSERT INTO realm (name, region) VALUES ("Галакронд", "EU");
INSERT INTO realm (name, region) VALUES ("Гром", "EU");
INSERT INTO realm (name, region) VALUES ("Свежеватель-Душ", "EU");
INSERT INTO realm (name, region) VALUES ("Zirkel des Cenarius", "EU");
INSERT INTO realm (name, region) VALUES ("Zul'jin", "EU");
INSERT INTO realm (name, region) VALUES ("Zuluhed", "EU");
INSERT INTO realm (name, region) VALUES ("Aegwynn", "US");
INSERT INTO realm (name, region) VALUES ("Aerie Peak", "US");
INSERT INTO realm (name, region) VALUES ("Agamaggan", "US");
INSERT INTO realm (name, region) VALUES ("Aggramar", "US");
INSERT INTO realm (name, region) VALUES ("Akama", "US");
INSERT INTO realm (name, region) VALUES ("Alexstrasza", "US");
INSERT INTO realm (name, region) VALUES ("Alleria", "US");
INSERT INTO realm (name, region) VALUES ("Altar of Storms", "US");
INSERT INTO realm (name, region) VALUES ("Alterac Mountains", "US");
INSERT INTO realm (name, region) VALUES ("Aman'Thul", "US");
INSERT INTO realm (name, region) VALUES ("Anasterian", "US");
INSERT INTO realm (name, region) VALUES ("Andorhal", "US");
INSERT INTO realm (name, region) VALUES ("Anetheron", "US");
INSERT INTO realm (name, region) VALUES ("Antonidas", "US");
INSERT INTO realm (name, region) VALUES ("Anub'arak", "US");
INSERT INTO realm (name, region) VALUES ("Anvilmar", "US");
INSERT INTO realm (name, region) VALUES ("Arathor", "US");
INSERT INTO realm (name, region) VALUES ("Archimonde", "US");
INSERT INTO realm (name, region) VALUES ("Area 52", "US");
INSERT INTO realm (name, region) VALUES ("Argent Dawn", "US");
INSERT INTO realm (name, region) VALUES ("Arthas", "US");
INSERT INTO realm (name, region) VALUES ("Arygos", "US");
INSERT INTO realm (name, region) VALUES ("Auchindoun", "US");
INSERT INTO realm (name, region) VALUES ("Azgalor", "US");
INSERT INTO realm (name, region) VALUES ("Azjol-Nerub", "US");
INSERT INTO realm (name, region) VALUES ("Azralon", "US");
INSERT INTO realm (name, region) VALUES ("Azshara", "US");
INSERT INTO realm (name, region) VALUES ("Azuremyst", "US");
INSERT INTO realm (name, region) VALUES ("Baelgun", "US");
INSERT INTO realm (name, region) VALUES ("Balnazzar", "US");
INSERT INTO realm (name, region) VALUES ("Barthilas", "US");
INSERT INTO realm (name, region) VALUES ("Benedictus", "US");
INSERT INTO realm (name, region) VALUES ("Beta Leveling Realm 01", "US");
INSERT INTO realm (name, region) VALUES ("Beta Leveling Realm 03", "US");
INSERT INTO realm (name, region) VALUES ("Beta Max Level PvP", "US");
INSERT INTO realm (name, region) VALUES ("Black Dragonflight", "US");
INSERT INTO realm (name, region) VALUES ("Blackhand", "US");
INSERT INTO realm (name, region) VALUES ("Blackrock", "US");
INSERT INTO realm (name, region) VALUES ("Blackwater Raiders", "US");
INSERT INTO realm (name, region) VALUES ("Blackwing Lair", "US");
INSERT INTO realm (name, region) VALUES ("Bladefist", "US");
INSERT INTO realm (name, region) VALUES ("Blade's Edge", "US");
INSERT INTO realm (name, region) VALUES ("Bleeding Hollow", "US");
INSERT INTO realm (name, region) VALUES ("Blood Furnace", "US");
INSERT INTO realm (name, region) VALUES ("Bloodhoof", "US");
INSERT INTO realm (name, region) VALUES ("Bloodscalp", "US");
INSERT INTO realm (name, region) VALUES ("Bonechewer", "US");
INSERT INTO realm (name, region) VALUES ("Borean Tundra", "US");
INSERT INTO realm (name, region) VALUES ("Boulderfist", "US");
INSERT INTO realm (name, region) VALUES ("Bronzebeard", "US");
INSERT INTO realm (name, region) VALUES ("Broxigar", "US");
INSERT INTO realm (name, region) VALUES ("Burning Blade", "US");
INSERT INTO realm (name, region) VALUES ("Burning Legion", "US");
INSERT INTO realm (name, region) VALUES ("Caelestrasz", "US");
INSERT INTO realm (name, region) VALUES ("Cairne", "US");
INSERT INTO realm (name, region) VALUES ("Cenarion Circle", "US");
INSERT INTO realm (name, region) VALUES ("Cenarius", "US");
INSERT INTO realm (name, region) VALUES ("Cho'gall", "US");
INSERT INTO realm (name, region) VALUES ("Chromaggus", "US");
INSERT INTO realm (name, region) VALUES ("Coilfang", "US");
INSERT INTO realm (name, region) VALUES ("Crushridge", "US");
INSERT INTO realm (name, region) VALUES ("Daggerspine", "US");
INSERT INTO realm (name, region) VALUES ("Dalaran", "US");
INSERT INTO realm (name, region) VALUES ("Dalvengyr", "US");
INSERT INTO realm (name, region) VALUES ("Dark Iron", "US");
INSERT INTO realm (name, region) VALUES ("Darkspear", "US");
INSERT INTO realm (name, region) VALUES ("Darrowmere", "US");
INSERT INTO realm (name, region) VALUES ("Dath'Remar", "US");
INSERT INTO realm (name, region) VALUES ("Dawnbringer", "US");
INSERT INTO realm (name, region) VALUES ("Deathwing", "US");
INSERT INTO realm (name, region) VALUES ("Demon Soul", "US");
INSERT INTO realm (name, region) VALUES ("Dentarg", "US");
INSERT INTO realm (name, region) VALUES ("Destromath", "US");
INSERT INTO realm (name, region) VALUES ("Dethecus", "US");
INSERT INTO realm (name, region) VALUES ("Detheroc", "US");
INSERT INTO realm (name, region) VALUES ("Doomhammer", "US");
INSERT INTO realm (name, region) VALUES ("Draenor", "US");
INSERT INTO realm (name, region) VALUES ("Dragonblight", "US");
INSERT INTO realm (name, region) VALUES ("Dragonmaw", "US");
INSERT INTO realm (name, region) VALUES ("Draka", "US");
INSERT INTO realm (name, region) VALUES ("Drakkari", "US");
INSERT INTO realm (name, region) VALUES ("Drak'Tharon", "US");
INSERT INTO realm (name, region) VALUES ("Drak'thul", "US");
INSERT INTO realm (name, region) VALUES ("Dreadmaul", "US");
INSERT INTO realm (name, region) VALUES ("Drenden", "US");
INSERT INTO realm (name, region) VALUES ("Dunemaul", "US");
INSERT INTO realm (name, region) VALUES ("Durotan", "US");
INSERT INTO realm (name, region) VALUES ("Duskwood", "US");
INSERT INTO realm (name, region) VALUES ("Earthen Ring", "US");
INSERT INTO realm (name, region) VALUES ("Echo Isles", "US");
INSERT INTO realm (name, region) VALUES ("Eitrigg", "US");
INSERT INTO realm (name, region) VALUES ("Eldre'Thalas", "US");
INSERT INTO realm (name, region) VALUES ("Elune", "US");
INSERT INTO realm (name, region) VALUES ("Emerald Dream", "US");
INSERT INTO realm (name, region) VALUES ("Eonar", "US");
INSERT INTO realm (name, region) VALUES ("Eredar", "US");
INSERT INTO realm (name, region) VALUES ("Executus", "US");
INSERT INTO realm (name, region) VALUES ("Exodar", "US");
INSERT INTO realm (name, region) VALUES ("Farstriders", "US");
INSERT INTO realm (name, region) VALUES ("Feathermoon", "US");
INSERT INTO realm (name, region) VALUES ("Fenris", "US");
INSERT INTO realm (name, region) VALUES ("Firetree", "US");
INSERT INTO realm (name, region) VALUES ("Fizzcrank", "US");
INSERT INTO realm (name, region) VALUES ("Frostmane", "US");
INSERT INTO realm (name, region) VALUES ("Frostmourne", "US");
INSERT INTO realm (name, region) VALUES ("Frostwolf", "US");
INSERT INTO realm (name, region) VALUES ("Galakrond", "US");
INSERT INTO realm (name, region) VALUES ("Gallywix", "US");
INSERT INTO realm (name, region) VALUES ("Garithos", "US");
INSERT INTO realm (name, region) VALUES ("Garona", "US");
INSERT INTO realm (name, region) VALUES ("Garrosh", "US");
INSERT INTO realm (name, region) VALUES ("Ghostlands", "US");
INSERT INTO realm (name, region) VALUES ("Gilneas", "US");
INSERT INTO realm (name, region) VALUES ("Gnomeregan", "US");
INSERT INTO realm (name, region) VALUES ("Goldrinn", "US");
INSERT INTO realm (name, region) VALUES ("Gorefiend", "US");
INSERT INTO realm (name, region) VALUES ("Gorgonnash", "US");
INSERT INTO realm (name, region) VALUES ("Greymane", "US");
INSERT INTO realm (name, region) VALUES ("Grizzly Hills", "US");
INSERT INTO realm (name, region) VALUES ("Gul'dan", "US");
INSERT INTO realm (name, region) VALUES ("Gundrak", "US");
INSERT INTO realm (name, region) VALUES ("Gurubashi", "US");
INSERT INTO realm (name, region) VALUES ("Hakkar", "US");
INSERT INTO realm (name, region) VALUES ("Haomarush", "US");
INSERT INTO realm (name, region) VALUES ("Hellscream", "US");
INSERT INTO realm (name, region) VALUES ("Hydraxis", "US");
INSERT INTO realm (name, region) VALUES ("Hyjal", "US");
INSERT INTO realm (name, region) VALUES ("Icecrown", "US");
INSERT INTO realm (name, region) VALUES ("Illidan", "US");
INSERT INTO realm (name, region) VALUES ("Jaedenar", "US");
INSERT INTO realm (name, region) VALUES ("Jubei'Thos", "US");
INSERT INTO realm (name, region) VALUES ("Kael'thas", "US");
INSERT INTO realm (name, region) VALUES ("Kalaran", "US");
INSERT INTO realm (name, region) VALUES ("Kalecgos", "US");
INSERT INTO realm (name, region) VALUES ("Kargath", "US");
INSERT INTO realm (name, region) VALUES ("Kel'Thuzad", "US");
INSERT INTO realm (name, region) VALUES ("Khadgar", "US");
INSERT INTO realm (name, region) VALUES ("Khaz Modan", "US");
INSERT INTO realm (name, region) VALUES ("Khaz'goroth", "US");
INSERT INTO realm (name, region) VALUES ("Kil'jaeden", "US");
INSERT INTO realm (name, region) VALUES ("Kilrogg", "US");
INSERT INTO realm (name, region) VALUES ("Kirin Tor", "US");
INSERT INTO realm (name, region) VALUES ("Korgath", "US");
INSERT INTO realm (name, region) VALUES ("Korialstrasz", "US");
INSERT INTO realm (name, region) VALUES ("Kul Tiras", "US");
INSERT INTO realm (name, region) VALUES ("Laughing Skull", "US");
INSERT INTO realm (name, region) VALUES ("Lethon", "US");
INSERT INTO realm (name, region) VALUES ("Lightbringer", "US");
INSERT INTO realm (name, region) VALUES ("Lightninghoof", "US");
INSERT INTO realm (name, region) VALUES ("Lightning's Blade", "US");
INSERT INTO realm (name, region) VALUES ("Llane", "US");
INSERT INTO realm (name, region) VALUES ("Lothar", "US");
INSERT INTO realm (name, region) VALUES ("Lycanthoth", "US");
INSERT INTO realm (name, region) VALUES ("Madoran", "US");
INSERT INTO realm (name, region) VALUES ("Maelstrom", "US");
INSERT INTO realm (name, region) VALUES ("Magtheridon", "US");
INSERT INTO realm (name, region) VALUES ("Maiev", "US");
INSERT INTO realm (name, region) VALUES ("Malfurion", "US");
INSERT INTO realm (name, region) VALUES ("Mal'Ganis", "US");
INSERT INTO realm (name, region) VALUES ("Malorne", "US");
INSERT INTO realm (name, region) VALUES ("Malygos", "US");
INSERT INTO realm (name, region) VALUES ("Mannoroth", "US");
INSERT INTO realm (name, region) VALUES ("Medivh", "US");
INSERT INTO realm (name, region) VALUES ("Misha", "US");
INSERT INTO realm (name, region) VALUES ("Mok'Nathal", "US");
INSERT INTO realm (name, region) VALUES ("Moon Guard", "US");
INSERT INTO realm (name, region) VALUES ("Moonrunner", "US");
INSERT INTO realm (name, region) VALUES ("Mug'thol", "US");
INSERT INTO realm (name, region) VALUES ("Muradin", "US");
INSERT INTO realm (name, region) VALUES ("Nagrand", "US");
INSERT INTO realm (name, region) VALUES ("Nathrezim", "US");
INSERT INTO realm (name, region) VALUES ("Nazgrel", "US");
INSERT INTO realm (name, region) VALUES ("Nazjatar", "US");
INSERT INTO realm (name, region) VALUES ("Nemesis", "US");
INSERT INTO realm (name, region) VALUES ("Ner'zhul", "US");
INSERT INTO realm (name, region) VALUES ("Nesingwary", "US");
INSERT INTO realm (name, region) VALUES ("Nordrassil", "US");
INSERT INTO realm (name, region) VALUES ("Norgannon", "US");
INSERT INTO realm (name, region) VALUES ("Onyxia", "US");
INSERT INTO realm (name, region) VALUES ("Perenolde", "US");
INSERT INTO realm (name, region) VALUES ("Proudmoore", "US");
INSERT INTO realm (name, region) VALUES ("Quel'dorei", "US");
INSERT INTO realm (name, region) VALUES ("Quel'Thalas", "US");
INSERT INTO realm (name, region) VALUES ("Ragnaros", "US");
INSERT INTO realm (name, region) VALUES ("Ravencrest", "US");
INSERT INTO realm (name, region) VALUES ("Ravenholdt", "US");
INSERT INTO realm (name, region) VALUES ("Rexxar", "US");
INSERT INTO realm (name, region) VALUES ("Rivendare", "US");
INSERT INTO realm (name, region) VALUES ("Runetotem", "US");
INSERT INTO realm (name, region) VALUES ("Sargeras", "US");
INSERT INTO realm (name, region) VALUES ("Saurfang", "US");
INSERT INTO realm (name, region) VALUES ("Scarlet Crusade", "US");
INSERT INTO realm (name, region) VALUES ("Scilla", "US");
INSERT INTO realm (name, region) VALUES ("Sen'jin", "US");
INSERT INTO realm (name, region) VALUES ("Sentinels", "US");
INSERT INTO realm (name, region) VALUES ("Shadow Council", "US");
INSERT INTO realm (name, region) VALUES ("Shadowmoon", "US");
INSERT INTO realm (name, region) VALUES ("Shadowsong", "US");
INSERT INTO realm (name, region) VALUES ("Shandris", "US");
INSERT INTO realm (name, region) VALUES ("Shattered Halls", "US");
INSERT INTO realm (name, region) VALUES ("Shattered Hand", "US");
INSERT INTO realm (name, region) VALUES ("Shu'halo", "US");
INSERT INTO realm (name, region) VALUES ("Silver Hand", "US");
INSERT INTO realm (name, region) VALUES ("Silvermoon", "US");
INSERT INTO realm (name, region) VALUES ("Sisters of Elune", "US");
INSERT INTO realm (name, region) VALUES ("Skullcrusher", "US");
INSERT INTO realm (name, region) VALUES ("Skywall", "US");
INSERT INTO realm (name, region) VALUES ("Smolderthorn", "US");
INSERT INTO realm (name, region) VALUES ("Spinebreaker", "US");
INSERT INTO realm (name, region) VALUES ("Spirestone", "US");
INSERT INTO realm (name, region) VALUES ("Staghelm", "US");
INSERT INTO realm (name, region) VALUES ("Steamwheedle Cartel", "US");
INSERT INTO realm (name, region) VALUES ("Stonemaul", "US");
INSERT INTO realm (name, region) VALUES ("Stormrage", "US");
INSERT INTO realm (name, region) VALUES ("Stormreaver", "US");
INSERT INTO realm (name, region) VALUES ("Stormscale", "US");
INSERT INTO realm (name, region) VALUES ("Suramar", "US");
INSERT INTO realm (name, region) VALUES ("Tanaris", "US");
INSERT INTO realm (name, region) VALUES ("Terenas", "US");
INSERT INTO realm (name, region) VALUES ("Terokkar", "US");
INSERT INTO realm (name, region) VALUES ("Thaurissan", "US");
INSERT INTO realm (name, region) VALUES ("The Forgotten Coast", "US");
INSERT INTO realm (name, region) VALUES ("The Scryers", "US");
INSERT INTO realm (name, region) VALUES ("The Underbog", "US");
INSERT INTO realm (name, region) VALUES ("The Venture Co", "US");
INSERT INTO realm (name, region) VALUES ("Thorium Brotherhood", "US");
INSERT INTO realm (name, region) VALUES ("Thrall", "US");
INSERT INTO realm (name, region) VALUES ("Thunderhorn", "US");
INSERT INTO realm (name, region) VALUES ("Thunderlord", "US");
INSERT INTO realm (name, region) VALUES ("Tichondrius", "US");
INSERT INTO realm (name, region) VALUES ("Tol Barad", "US");
INSERT INTO realm (name, region) VALUES ("Tortheldrin", "US");
INSERT INTO realm (name, region) VALUES ("Trollbane", "US");
INSERT INTO realm (name, region) VALUES ("Turalyon", "US");
INSERT INTO realm (name, region) VALUES ("Twisting Nether", "US");
INSERT INTO realm (name, region) VALUES ("Uldaman", "US");
INSERT INTO realm (name, region) VALUES ("Uldum", "US");
INSERT INTO realm (name, region) VALUES ("Undermine", "US");
INSERT INTO realm (name, region) VALUES ("Ursin", "US");
INSERT INTO realm (name, region) VALUES ("Uther", "US");
INSERT INTO realm (name, region) VALUES ("Vashj", "US");
INSERT INTO realm (name, region) VALUES ("Vek'nilash", "US");
INSERT INTO realm (name, region) VALUES ("Velen", "US");
INSERT INTO realm (name, region) VALUES ("Warsong", "US");
INSERT INTO realm (name, region) VALUES ("Whisperwind", "US");
INSERT INTO realm (name, region) VALUES ("Wildhammer", "US");
INSERT INTO realm (name, region) VALUES ("Windrunner", "US");
INSERT INTO realm (name, region) VALUES ("Winterhoof", "US");
INSERT INTO realm (name, region) VALUES ("Wyrmrest Accord", "US");
INSERT INTO realm (name, region) VALUES ("Ysera", "US");
INSERT INTO realm (name, region) VALUES ("Ysondre", "US");
INSERT INTO realm (name, region) VALUES ("Zangarmarsh", "US");
INSERT INTO realm (name, region) VALUES ("Zul'jin", "US");
INSERT INTO realm (name, region) VALUES ("Zuluhed", "US");